/*
 * Notification DB Script
 */
CREATE TABLE IF NOT EXISTS LOCAL_NOTIFICATION (
  ID              BIGSERIAL PRIMARY KEY,
  TYPE            TEXT,
  TEMPLATE_ID     TEXT,
  RECIPIENT_EMAIL TEXT,
  NAME_VALUE_JSON TEXT,
  STATUS          TEXT,
  RETRY_COUNT     INTEGER,
  CREATED         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);