/*
 * Notification DB Script
 */
CREATE TABLE IF NOT EXISTS LOCAL_NOTIFICATION (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  TEMPLATE_ID TEXT,
  RECIPIENT_EMAIL TEXT,
  NAME_VALUE_JSON TEXT,
  RETRY_SEND INTEGER,
  RETRY_COUNT INTEGER);